spring:
  application:
    name: order-service

    # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: OrderHikariPool

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

order:
  inventory-service-url: http://localhost:8081
  payment-service-url: http://localhost:8083


server:
  port: 8082
  shutdown: graceful



# ACTUATOR &OBSERVABILITY
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
  info:
    git:
      mode: full
    env:
      enabled: true
    build:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
    instances:
      inventory:
        baseConfig: default
      payment:
        baseConfig: default